{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO0GKP+dnWcmUWrQhg/2l5Q"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "print(\"Hello World\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KHkxMXD9PVPH",
        "outputId": "6e1989e8-9e29-4d37-f2f3-8e63a936f122"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Hello World\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "class Libro:\n",
        "    def __init__(self, titulo: str, autor: str, isbn: str):\n",
        "        self.titulo = titulo\n",
        "        self.autor = autor\n",
        "        self.isbn = isbn\n",
        "        self.disponible = True  # Inicialmente, el libro está disponible\n",
        "\n",
        "    def prestar(self):\n",
        "        if self.disponible:\n",
        "            self.disponible = False\n",
        "            print(f\"El libro '{self.titulo}' ha sido prestado.\")\n",
        "        else:\n",
        "            print(f\"El libro '{self.titulo}' ya está prestado.\")\n",
        "\n",
        "    def devolver(self):\n",
        "        if not self.disponible:\n",
        "            self.disponible = True\n",
        "            print(f\"El libro '{self.titulo}' ha sido devuelto.\")\n",
        "        else:\n",
        "            print(f\"El libro '{self.titulo}' ya estaba disponible.\")\n",
        "\n",
        "    def mostrar(self):\n",
        "        estado = \"Disponible\" if self.disponible else \"Prestado\"\n",
        "        return f\"Título: {self.titulo}, Autor: {self.autor}, ISBN: {self.isbn}, Estado: {estado}\"\n",
        "\n",
        "\n",
        "# Clase principal para gestionar la biblioteca\n",
        "class Biblioteca:\n",
        "    def __init__(self):\n",
        "        self.libros = []  # Lista para almacenar objetos de la clase Libro\n",
        "\n",
        "    def agregar_libro(self):\n",
        "        titulo = input(\"Ingrese el título del libro: \")\n",
        "        autor = input(\"Ingrese el autor del libro: \")\n",
        "        isbn = input(\"Ingrese el ISBN del libro: \")\n",
        "        nuevo_libro = Libro(titulo, autor, isbn)\n",
        "        self.libros.append(nuevo_libro)\n",
        "        print(f\"El libro '{titulo}' ha sido agregado a la biblioteca.\")\n",
        "\n",
        "    def prestar_libro(self):\n",
        "        isbn = input(\"Ingrese el ISBN del libro que desea prestar: \")\n",
        "        libro = self.buscar_por_isbn(isbn)\n",
        "        if libro:\n",
        "            libro.prestar()\n",
        "        else:\n",
        "            print(\"No se encontró ningún libro con ese ISBN.\")\n",
        "\n",
        "    def devolver_libro(self):\n",
        "        isbn = input(\"Ingrese el ISBN del libro que desea devolver: \")\n",
        "        libro = self.buscar_por_isbn(isbn)\n",
        "        if libro:\n",
        "            libro.devolver()\n",
        "        else:\n",
        "            print(\"No se encontró ningún libro con ese ISBN.\")\n",
        "\n",
        "    def mostrar_libros(self):\n",
        "        if not self.libros:\n",
        "            print(\"No hay libros en la biblioteca.\")\n",
        "        else:\n",
        "            print(\"\\n--- Lista de libros ---\")\n",
        "            for libro in self.libros:\n",
        "                print(libro.mostrar())\n",
        "            print(\"------------------------\")\n",
        "\n",
        "    def buscar_por_isbn(self, isbn):\n",
        "        for libro in self.libros:\n",
        "            if libro.isbn == isbn:\n",
        "                return libro\n",
        "        return None\n",
        "\n",
        "    def buscar_libro(self):\n",
        "        isbn = input(\"Ingrese el ISBN del libro que desea buscar: \")\n",
        "        libro = self.buscar_por_isbn(isbn)\n",
        "        if libro:\n",
        "            print(\"\\n--- Resultado de la búsqueda ---\")\n",
        "            print(libro.mostrar())\n",
        "            print(\"--------------------------------\")\n",
        "        else:\n",
        "            print(\"No se encontró ningún libro con ese ISBN.\")\n",
        "\n",
        "\n",
        "# Función principal para interactuar con el usuario\n",
        "def main():\n",
        "    biblioteca = Biblioteca()\n",
        "\n",
        "    while True:\n",
        "        print(\"\\nBienvenido al Sistema de Gestión de Biblioteca\")\n",
        "        print(\"1. Agregar libro\")\n",
        "        print(\"2. Prestar libro\")\n",
        "        print(\"3. Devolver libro\")\n",
        "        print(\"4. Mostrar libros\")\n",
        "        print(\"5. Buscar libro\")\n",
        "        print(\"6. Salir\")\n",
        "\n",
        "        opcion = input(\"Elige una opción: \")\n",
        "\n",
        "        if opcion == \"1\":\n",
        "            biblioteca.agregar_libro()\n",
        "        elif opcion == \"2\":\n",
        "            biblioteca.prestar_libro()\n",
        "        elif opcion == \"3\":\n",
        "            biblioteca.devolver_libro()\n",
        "        elif opcion == \"4\":\n",
        "            biblioteca.mostrar_libros()\n",
        "        elif opcion == \"5\":\n",
        "            biblioteca.buscar_libro()\n",
        "        elif opcion == \"6\":\n",
        "            print(\"Gracias por usar el Sistema de Gestión de Biblioteca. ¡Hasta luego!\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Opción inválida. Por favor, intenta nuevamente.\")\n",
        "\n",
        "\n",
        "# Ejecutar el programa\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "9mB29jheNyr-",
        "outputId": "95bc9013-da0f-42dc-cb6a-b6d529feb18a"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 1\n",
            "Ingrese el título del libro: El Quijote\n",
            "Ingrese el autor del libro: Cervantes\n",
            "Ingrese el ISBN del libro: 12345\n",
            "El libro 'El Quijote' ha sido agregado a la biblioteca.\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 4\n",
            "\n",
            "--- Lista de libros ---\n",
            "Título: El Quijote, Autor: Cervantes, ISBN: 12345, Estado: Disponible\n",
            "------------------------\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 2\n",
            "Ingrese el ISBN del libro que desea prestar: 12345\n",
            "El libro 'El Quijote' ha sido prestado.\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 4\n",
            "\n",
            "--- Lista de libros ---\n",
            "Título: El Quijote, Autor: Cervantes, ISBN: 12345, Estado: Prestado\n",
            "------------------------\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 3\n",
            "Ingrese el ISBN del libro que desea devolver: 12345\n",
            "El libro 'El Quijote' ha sido devuelto.\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 5\n",
            "Ingrese el ISBN del libro que desea buscar: 12345\n",
            "\n",
            "--- Resultado de la búsqueda ---\n",
            "Título: El Quijote, Autor: Cervantes, ISBN: 12345, Estado: Disponible\n",
            "--------------------------------\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 4\n",
            "\n",
            "--- Lista de libros ---\n",
            "Título: El Quijote, Autor: Cervantes, ISBN: 12345, Estado: Disponible\n",
            "------------------------\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 4\n",
            "\n",
            "--- Lista de libros ---\n",
            "Título: El Quijote, Autor: Cervantes, ISBN: 12345, Estado: Disponible\n",
            "------------------------\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n",
            "Elige una opción: 12346\n",
            "Opción inválida. Por favor, intenta nuevamente.\n",
            "\n",
            "Bienvenido al Sistema de Gestión de Biblioteca\n",
            "1. Agregar libro\n",
            "2. Prestar libro\n",
            "3. Devolver libro\n",
            "4. Mostrar libros\n",
            "5. Buscar libro\n",
            "6. Salir\n"
          ]
        }
      ]
    }
  ]
}